export interface NIMModel {
  id: string;
  name: string;
  description: string;
  category: ModelCategory;
  contextLength: number;
  supportsStreaming: boolean;
  supportsFunctionCalling: boolean;
  supportsVision?: boolean;
  supportsImageGeneration?: boolean;
  maxTokens?: number;
  recommendedUseCases?: string[];
  parameters?: {
    maxImagesPerRequest?: number;
    supportedResolutions?: string[];
    supportedAspectRatios?: string[];
    supportedSamplers?: string[];
    supportedSchedulers?: string[];
  };

  // Licensing & Commercial Use
  license: string;
  commercialUse: boolean;
  thirdPartyModel: boolean;

  // Hardware Requirements
  minGpuRequirements: string[];
  supportedHardware: string[];
  runtimeEngines: string[];

  // Benchmark Scores
  benchmarks?: {
    coding?: {
      sweBench?: number;
      terminalBench?: number;
      liveCodeBench?: number;
    };
    reasoning?: {
      gpqa?: number;
      aime?: number;
      hmmt?: number;
    };
    agentic?: {
      tauBench?: number;
      browseComp?: number;
      sweBenchVerified?: number;
    };
    vision?: {
      mmmu?: number;
      mathVision?: number;
    };
  };

  // Image Generation Specifications
  imageGenSpecs?: {
    supportedResolutions: string[];
    supportedAspectRatios: string[];
    maxImagesPerRequest: number;
    recommendedSamplers: string[];
    recommendedSchedulers: string[];
    defaultSteps: number;
    defaultCfgScale: number;
    supportsNegativePrompt: boolean;
    supportsImageToImage: boolean;
    supportsInpainting: boolean;
    supportsControlNet: boolean;
  };

  // Deployment & Integration
  deploymentNotes?: string;
  outputMaxTokens?: number;
  supportsReasoning?: boolean;
  reasoningModes?: string[];

  // Special Capabilities
  supportsMultimodalInput?: boolean;
  supportsVideoInput?: boolean;
  supportsStructuredOutput?: boolean;
  supportedLanguages?: string[];

  // Use Case Tags
  tags: string[];
}

export type ModelCategory =
  | "language"
  | "embedding"
  | "reranking"
  | "vision"
  | "code"
  | "multimodal"
  | "image_generation";

export const NIM_MODELS: Record<string, NIMModel> = {
  // === LLMs ===
  "meta/llama-3.1-405b-instruct": {
    id: "meta/llama-3.1-405b-instruct",
    name: "Llama 3.1 405B Instruct",
    description: "Meta's largest Llama 3.1 model, best for complex reasoning",
    category: "language",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 128000,
    license: "Llama 3.1 Community License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["reasoning", "coding", "multilingual", "general-purpose"],
    supportsReasoning: false,
    supportedLanguages: ["en", "es", "fr", "de", "it", "pt", "hi", "zh", "ja", "ko"],
  },
  "meta/llama-3.1-70b-instruct": {
    id: "meta/llama-3.1-70b-instruct",
    name: "Llama 3.1 70B Instruct",
    description: "Balanced performance and efficiency",
    category: "language",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 128000,
    license: "Llama 3.1 Community License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["2x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["reasoning", "coding", "multilingual", "general-purpose", "efficient"],
    supportsReasoning: false,
    supportedLanguages: ["en", "es", "fr", "de", "it", "pt", "hi", "zh", "ja", "ko"],
  },
  "meta/llama-3.1-8b-instruct": {
    id: "meta/llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    description: "Fast and efficient for simpler tasks",
    category: "language",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    license: "Llama 3.1 Community License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["efficient", "fast", "multilingual", "general-purpose"],
    supportsReasoning: false,
    supportedLanguages: ["en", "es", "fr", "de", "it", "pt", "hi", "zh", "ja", "ko"],
  },
  "meta/llama-3.2-90b-vision-instruct": {
    id: "meta/llama-3.2-90b-vision-instruct",
    name: "Llama 3.2 90B Vision Instruct",
    description: "Multimodal model with vision capabilities",
    category: "vision",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsVision: true,
    license: "Llama 3.2 Community License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["2x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["vision", "multimodal", "image-understanding", "ocr", "document-analysis"],
    supportsReasoning: false,
    supportedLanguages: ["en", "es", "fr", "de", "it", "pt", "hi", "zh", "ja", "ko"],
    supportsMultimodalInput: true,
    supportsStructuredOutput: true,
  },
  "meta/llama-3.2-11b-vision-instruct": {
    id: "meta/llama-3.2-11b-vision-instruct",
    name: "Llama 3.2 11B Vision Instruct",
    description: "Efficient multimodal model",
    category: "vision",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsVision: true,
    license: "Llama 3.2 Community License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["vision", "multimodal", "efficient", "image-understanding", "ocr"],
    supportsReasoning: false,
    supportedLanguages: ["en", "es", "fr", "de", "it", "pt", "hi", "zh", "ja", "ko"],
    supportsMultimodalInput: true,
    supportsStructuredOutput: true,
  },
  "mistralai/mistral-large-2-instruct": {
    id: "mistralai/mistral-large-2-instruct",
    name: "Mistral Large 2",
    description: "Mistral's flagship model with excellent reasoning",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    license: "Mistral Research License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["2x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["reasoning", "coding", "multilingual", "general-purpose"],
    supportsReasoning: false,
    supportedLanguages: ["en", "fr", "es", "de", "it", "pt", "nl", "pl", "ru", "zh", "ja", "ko", "ar"],
  },
  "mistralai/mixtral-8x22b-instruct-v0.1": {
    id: "mistralai/mixtral-8x22b-instruct-v0.1",
    name: "Mixtral 8x22B Instruct",
    description: "MoE model with excellent performance",
    category: "language",
    contextLength: 65536,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    license: "Apache 2.0",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["moe", "reasoning", "coding", "multilingual", "efficient"],
    supportsReasoning: false,
    supportedLanguages: ["en", "fr", "es", "de", "it", "pt", "nl", "pl", "ru", "zh", "ja", "ko", "ar"],
  },
  "mistralai/mixtral-8x7b-instruct-v0.1": {
    id: "mistralai/mixtral-8x7b-instruct-v0.1",
    name: "Mixtral 8x7B Instruct",
    description: "Efficient MoE model",
    category: "language",
    contextLength: 32768,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "Apache 2.0",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["2x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["moe", "efficient", "multilingual", "general-purpose"],
    supportsReasoning: false,
    supportedLanguages: ["en", "fr", "es", "de", "it", "pt", "nl", "pl", "ru", "zh", "ja", "ko", "ar"],
  },
  "microsoft/phi-3.5-mini-instruct": {
    id: "microsoft/phi-3.5-mini-instruct",
    name: "Phi-3.5 Mini Instruct",
    description: "Microsoft's efficient small model",
    category: "language",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x RTX 3090 24GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere", "Ada"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["efficient", "small", "long-context", "general-purpose"],
    supportsReasoning: false,
    supportedLanguages: ["en"],
  },
  "microsoft/phi-3-medium-128k-instruct": {
    id: "microsoft/phi-3-medium-128k-instruct",
    name: "Phi-3 Medium 128K Instruct",
    description: "Microsoft's medium model with long context",
    category: "language",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["medium", "long-context", "general-purpose"],
    supportsReasoning: false,
    supportedLanguages: ["en"],
  },
  "google/gemma-2-27b-it": {
    id: "google/gemma-2-27b-it",
    name: "Gemma 2 27B IT",
    description: "Google's Gemma 2 model",
    category: "language",
    contextLength: 8192,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "Gemma Terms of Use",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["multilingual", "general-purpose", "efficient"],
    supportsReasoning: false,
    supportedLanguages: ["en", "de", "fr", "es", "it", "pt", "ru", "zh", "ja", "ko", "ar", "hi"],
  },
  "google/gemma-2-9b-it": {
    id: "google/gemma-2-9b-it",
    name: "Gemma 2 9B IT",
    description: "Google's efficient Gemma 2 model",
    category: "language",
    contextLength: 8192,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "Gemma Terms of Use",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x RTX 3090 24GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere", "Ada"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["efficient", "multilingual", "general-purpose", "small"],
    supportsReasoning: false,
    supportedLanguages: ["en", "de", "fr", "es", "it", "pt", "ru", "zh", "ja", "ko", "ar", "hi"],
  },
  "qwen/qwen2.5-72b-instruct": {
    id: "qwen/qwen2.5-72b-instruct",
    name: "Qwen 2.5 72B Instruct",
    description: "Alibaba's Qwen 2.5 large model",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    license: "Qwen Research License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["2x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["reasoning", "coding", "multilingual", "long-context"],
    supportsReasoning: false,
    supportedLanguages: ["en", "zh", "ja", "ko", "fr", "de", "es", "ru", "ar", "pt", "it", "nl", "pl", "tr", "vi", "th", "id", "ms"],
  },
  "qwen/qwen2.5-coder-32b-instruct": {
    id: "qwen/qwen2.5-coder-32b-instruct",
    name: "Qwen 2.5 Coder 32B",
    description: "Specialized coding model",
    category: "code",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "Qwen Research License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["1x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["coding", "code-generation", "debugging", "refactoring", "multilingual"],
    supportsReasoning: false,
    supportedLanguages: ["en", "zh", "ja", "ko", "fr", "de", "es", "ru", "ar", "pt", "it", "nl", "pl", "tr", "vi", "th", "id", "ms"],
  },
  "nvidia/llama-3.1-nemotron-70b-instruct": {
    id: "nvidia/llama-3.1-nemotron-70b-instruct",
    name: "Nemotron 70B Instruct",
    description: "NVIDIA's fine-tuned Llama with RLHF",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "NVIDIA Open Model License",
    commercialUse: true,
    thirdPartyModel: false,
    minGpuRequirements: ["2x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["reasoning", "chat", "instruction-following"],
    supportsReasoning: false,
    supportedLanguages: ["en"],
  },
  // === Nemotron 3 Ultra ===
  "nvidia/nemotron-3-ultra-550b-a55b": {
    id: "nvidia/nemotron-3-ultra-550b-a55b",
    name: "Nemotron 3 Ultra",
    description: "NVIDIA's flagship 550B parameter model with advanced reasoning and coding capabilities",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Complex reasoning",
      "Advanced coding",
      "Mathematical problem solving",
      "Scientific research",
      "Enterprise applications",
    ],
    license: "OpenMDW-1.1",
    commercialUse: true,
    thirdPartyModel: false,
    minGpuRequirements: ["4x B200", "4x GB200", "8x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM", "SGLang"],
    benchmarks: {
      coding: { sweBench: 71.9, terminalBench: 56.4, liveCodeBench: 0 },
      reasoning: { gpqa: 87.0, aime: 0, hmmt: 0 },
      agentic: { tauBench: 70.9, browseComp: 44.4, sweBenchVerified: 71.9 },
    },
    tags: ["frontier", "reasoning", "coding", "agentic", "long-context", "multilingual", "scientific"],
    supportsReasoning: true,
    reasoningModes: ["enable_thinking=true", "enable_thinking=false"],
    supportedLanguages: ["en", "fr", "es", "it", "de", "ja", "ko", "hi", "pt", "zh"],
  },
  "nvidia/nemotron-3-ultra-550b-a55b-instruct": {
    id: "nvidia/nemotron-3-ultra-550b-a55b-instruct",
    name: "Nemotron 3 Ultra Instruct",
    description: "Instruction-tuned Nemotron 3 Ultra for chat and task completion",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Conversational AI",
      "Task automation",
      "Code generation",
      "Analysis and reasoning",
    ],
    license: "OpenMDW-1.1",
    commercialUse: true,
    thirdPartyModel: false,
    minGpuRequirements: ["4x B200", "4x GB200", "8x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM", "SGLang"],
    benchmarks: {
      coding: { sweBench: 71.9, terminalBench: 56.4, liveCodeBench: 0 },
      reasoning: { gpqa: 87.0, aime: 0, hmmt: 0 },
      agentic: { tauBench: 70.9, browseComp: 44.4, sweBenchVerified: 71.9 },
    },
    tags: ["frontier", "reasoning", "coding", "agentic", "long-context", "multilingual", "chat"],
    supportsReasoning: true,
    reasoningModes: ["enable_thinking=true", "enable_thinking=false"],
    supportedLanguages: ["en", "fr", "es", "it", "de", "ja", "ko", "hi", "pt", "zh"],
  },
  // === MiniMax ===
  "minimaxai/minimax-m3": {
    id: "minimaxai/minimax-m3",
    name: "MiniMax M3",
    description: "MiniMax's advanced multimodal MoE model with 428B total parameters (22B active) for long-context reasoning, agentic workflows, and creative tasks. Supports text, image, and video inputs.",
    category: "multimodal",
    contextLength: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    supportsMultimodalInput: true,
    supportsVideoInput: true,
    maxTokens: 256000,
    recommendedUseCases: [
      "Long-form video understanding (up to 30 min)",
      "Long-horizon coding (8+ hours)",
      "Agentic and tool-use workflows",
      "Design and creative tasks",
      "Multimodal reasoning",
    ],
    license: "Non-Commercial MiniMax License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "4x B200", "4x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["multimodal", "video", "long-context", "coding", "agentic", "creative", "moe"],
    supportsReasoning: false,
    supportedLanguages: ["en", "zh"],
  },
  // === Kimi ===
  "moonshotai/kimi-k2.6": {
    id: "moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    description: "Moonshot AI's open-source native multimodal agentic model with 1T total parameters (32B active). Supports long-horizon coding, 300 sub-agents, 4000 coordinated steps, and multimodal inputs via MoonViT vision encoder.",
    category: "multimodal",
    contextLength: 256000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    supportsMultimodalInput: true,
    supportsVideoInput: true,
    maxTokens: 1000000,
    recommendedUseCases: [
      "Long-horizon coding (Rust, Go, Python, frontend, DevOps)",
      "Agentic orchestration (300 sub-agents, 4000 steps)",
      "Visual reasoning with image/video",
      "Complex multi-step problem solving",
      "Autonomous background task execution",
    ],
    license: "Modified MIT License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "4x B200", "8x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM"],
    benchmarks: {
      coding: { sweBench: 80.2, terminalBench: 66.7, liveCodeBench: 89.6 },
      reasoning: { gpqa: 90.5, aime: 96.4, hmmt: 92.7 },
      agentic: { tauBench: 0, browseComp: 83.2, sweBenchVerified: 80.2 },
      vision: { mmmu: 79.4, mathVision: 87.4 },
    },
    tags: ["multimodal", "coding", "agentic", "reasoning", "long-horizon", "vision", "commercial"],
    supportsReasoning: false,
    supportedLanguages: ["en", "zh"],
  },
  // === DeepSeek ===
  "deepseek-ai/deepseek-v4-pro": {
    id: "deepseek-ai/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    description: "DeepSeek's latest Mixture of Experts model with 1.6T total parameters (49B activated). Hybrid attention (CSA + HCA) achieving 27% inference FLOPs vs V3.2 at 1M context. Three reasoning modes: Non-think, Think High, Think Max.",
    category: "language",
    contextLength: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Advanced coding",
      "Mathematical reasoning",
      "Scientific computing",
      "Complex problem solving",
      "Agentic AI applications",
    ],
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x H100 80GB", "4x H200", "4x B200"],
    supportedHardware: ["Ampere", "Blackwell", "Hopper"],
    runtimeEngines: ["Transformers", "vLLM"],
    benchmarks: {
      coding: { sweBench: 80.6, terminalBench: 67.9, liveCodeBench: 93.5 },
      reasoning: { gpqa: 90.1, aime: 0, hmmt: 95.2 },
      agentic: { tauBench: 0, browseComp: 83.4, sweBenchVerified: 80.6 },
    },
    tags: ["moe", "reasoning", "coding", "math", "long-context", "agentic", "commercial"],
    supportsReasoning: true,
    reasoningModes: ["non-think", "think-high", "think-max"],
    supportedLanguages: ["en", "zh"],
  },
  "deepseek-ai/deepseek-v4-pro-chat": {
    id: "deepseek-ai/deepseek-v4-pro-chat",
    name: "DeepSeek V4 Pro Chat",
    description: "Chat-optimized variant of DeepSeek V4 Pro",
    category: "language",
    contextLength: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Conversational AI",
      "Code assistance",
      "Technical Q&A",
    ],
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x H100 80GB", "4x H200", "4x B200"],
    supportedHardware: ["Ampere", "Blackwell", "Hopper"],
    runtimeEngines: ["Transformers", "vLLM"],
    tags: ["moe", "reasoning", "coding", "chat", "long-context", "commercial"],
    supportsReasoning: true,
    reasoningModes: ["non-think", "think-high", "think-max"],
    supportedLanguages: ["en", "zh"],
  },
  // === GLM ===
  "z-ai/glm-5.1": {
    id: "z-ai/glm-5.1",
    name: "GLM-5.1",
    description: "Z.ai's next-generation flagship with 754B parameters (DSA architecture). Significantly stronger coding than GLM-5, sustains optimization over hundreds of reasoning rounds and thousands of tool calls.",
    category: "code",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Software development",
      "Code generation",
      "Debugging and refactoring",
      "System architecture",
      "Technical documentation",
      "Agentic workflows",
    ],
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "4x B200"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM"],
    benchmarks: {
      coding: { sweBench: 58.4, terminalBench: 63.5, liveCodeBench: 0 },
      reasoning: { gpqa: 86.2, aime: 95.3, hmmt: 82.6 },
      agentic: { tauBench: 70.6, browseComp: 79.3, sweBenchVerified: 0 },
    },
    tags: ["coding", "agentic", "reasoning", "software-engineering", "commercial", "dsa"],
    supportsReasoning: true,
    reasoningModes: ["enabled", "disabled"],
    supportedLanguages: ["en", "zh"],
  },
  "z-ai/glm-5.1-chat": {
    id: "z-ai/glm-5.1-chat",
    name: "GLM-5.1 Chat",
    description: "Chat-optimized variant of GLM-5.1",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Conversational AI",
      "Code assistance",
      "Technical discussions",
    ],
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "4x B200"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM"],
    tags: ["coding", "chat", "agentic", "reasoning", "commercial"],
    supportsReasoning: true,
    reasoningModes: ["enabled", "disabled"],
    supportedLanguages: ["en", "zh"],
  },
  // === Qwen ===
  "qwen/qwen3.5-397b-a17b": {
    id: "qwen/qwen3.5-397b-a17b",
    name: "Qwen 3.5 397B",
    description: "Alibaba's massive 397B parameter MoE model with multimodal capabilities (text, image, video). Listed in NVIDIA Multimodal APIs.",
    category: "multimodal",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    supportsMultimodalInput: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Large-scale reasoning",
      "Multilingual processing",
      "Complex analysis",
      "Enterprise applications",
      "Multimodal understanding",
    ],
    license: "Qwen Research License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "8x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM"],
    tags: ["moe", "multimodal", "reasoning", "coding", "large-scale", "multilingual"],
    supportsReasoning: false,
    supportedLanguages: ["en", "zh", "ja", "ko", "fr", "de", "es", "ru", "ar", "pt", "it", "nl", "pl", "tr", "vi", "th", "id", "ms"],
  },
  "qwen/qwen3.5-397b-a17b-chat": {
    id: "qwen/qwen3.5-397b-a17b-chat",
    name: "Qwen 3.5 397B Chat",
    description: "Chat-tuned variant of Qwen 3.5 397B",
    category: "multimodal",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    supportsMultimodalInput: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Conversational AI",
      "Multilingual chat",
      "Code assistance",
    ],
    license: "Qwen Research License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "8x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM"],
    tags: ["moe", "multimodal", "chat", "reasoning", "coding", "large-scale"],
    supportsReasoning: false,
    supportedLanguages: ["en", "zh", "ja", "ko", "fr", "de", "es", "ru", "ar", "pt", "it", "nl", "pl", "tr", "vi", "th", "id", "ms"],
  },
  // === Mistral ===
  "mistralai/mistral-large-3-675b-instruct-2512": {
    id: "mistralai/mistral-large-3-675b-instruct-2512",
    name: "Mistral Large 3 675B",
    description: "Mistral's flagship 675B parameter model (Dec 2025) with advanced reasoning and multimodal capabilities. Listed in NVIDIA Visual Models APIs.",
    category: "multimodal",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    supportsMultimodalInput: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Complex reasoning",
      "Advanced coding",
      "Multilingual tasks",
      "Enterprise deployment",
      "Multimodal understanding",
    ],
    license: "Mistral Research License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "8x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["frontier", "reasoning", "coding", "multilingual", "multimodal", "large-scale"],
    supportsReasoning: false,
    supportedLanguages: ["en", "fr", "es", "de", "it", "pt", "nl", "pl", "ru", "zh", "ja", "ko", "ar"],
  },
  "mistralai/mistral-large-3-675b-instruct-2512-chat": {
    id: "mistralai/mistral-large-3-675b-instruct-2512-chat",
    name: "Mistral Large 3 675B Chat",
    description: "Chat-optimized variant of Mistral Large 3",
    category: "multimodal",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    supportsVision: true,
    supportsMultimodalInput: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Conversational AI",
      "Task automation",
      "Code generation",
    ],
    license: "Mistral Research License",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "8x H100 80GB"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["frontier", "chat", "reasoning", "coding", "multimodal", "large-scale"],
    supportsReasoning: false,
    supportedLanguages: ["en", "fr", "es", "de", "it", "pt", "nl", "pl", "ru", "zh", "ja", "ko", "ar"],
  },
  // === OpenAI GPT-OSS ===
  "openai/gpt-oss-120b": {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS 120B",
    description: "OpenAI's open-weight 120B parameter model. Available on NVIDIA NIM for open-source deployment and research.",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Open-source deployment",
      "Research and experimentation",
      "Custom fine-tuning",
      "Enterprise applications",
    ],
    license: "Apache 2.0",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["2x H100 80GB", "4x A100 40GB"],
    supportedHardware: ["Hopper", "Ampere", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["open-weight", "research", "fine-tuning", "commercial", "open-source"],
    supportsReasoning: false,
    supportedLanguages: ["en"],
  },
  "openai/gpt-oss-120b-chat": {
    id: "openai/gpt-oss-120b-chat",
    name: "GPT-OSS 120B Chat",
    description: "Chat-tuned variant of GPT-OSS 120B",
    category: "language",
    contextLength: 131072,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    maxTokens: 131072,
    recommendedUseCases: [
      "Conversational AI",
      "General purpose chat",
      "Code assistance",
    ],
    license: "Apache 2.0",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["2x H100 80GB", "4x A100 40GB"],
    supportedHardware: ["Hopper", "Ampere", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["open-weight", "chat", "research", "fine-tuning", "commercial"],
    supportsReasoning: false,
    supportedLanguages: ["en"],
  },
  // === DiffusionGemma ===
  "google/diffusiongemma-26b-a4b-it": {
    id: "google/diffusiongemma-26b-a4b-it",
    name: "DiffusionGemma 26B A4B IT",
    description: "Google DeepMind's diffusion-based multimodal generative model (25.2B total, 3.8B active). Processes text, image, and video inputs to produce text output via discrete diffusion. 256K context, 35+ languages, native function calling, >1100 tok/s on H100.",
    category: "multimodal",
    contextLength: 262144,
    supportsStreaming: false,
    supportsFunctionCalling: true,
    supportsVision: true,
    supportsMultimodalInput: true,
    supportsVideoInput: true,
    maxTokens: 262144,
    recommendedUseCases: [
      "Conversational AI and chatbots",
      "Text summarization",
      "Code generation and step-by-step reasoning",
      "Image and document understanding (OCR, chart comprehension, PDF parsing)",
      "Video content analysis (up to 60s at 1fps)",
      "Agentic workflows with native function calling",
      "Multilingual NLP tasks across 35+ languages",
    ],
    license: "Apache 2.0",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x H100 80GB", "1x B200", "1x RTX 5090"],
    supportedHardware: ["Ampere", "Blackwell", "Hopper"],
    runtimeEngines: ["Transformers", "vLLM", "Unsloth"],
    benchmarks: {
      reasoning: { gpqa: 73.2, aime: 69.1, hmmt: 0 },
      vision: { mmmu: 54.3, mathVision: 70.5 },
    },
    tags: ["multimodal", "diffusion", "video", "multilingual", "agentic", "fast", "commercial"],
    supportsReasoning: true,
    reasoningModes: ["<|think|>", "disabled"],
    supportedLanguages: ["en", "zh", "ja", "ko", "fr", "de", "es", "ru", "ar", "pt", "it", "hi", "th", "vi", "id", "ms", "tr", "pl", "nl", "uk", "cs", "sk", "hu", "ro", "bg", "hr", "sl", "et", "lv", "lt", "mt", "ga", "cy"],
  },
  "z-ai/glm-4-9b-chat": {
    id: "z-ai/glm-4-9b-chat",
    name: "GLM-4 9B Chat",
    description: "Zhipu AI's GLM-4 model, strong multilingual and reasoning capabilities",
    category: "language",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    license: "Z.ai License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM"],
    tags: ["multilingual", "reasoning", "general-purpose", "efficient"],
    supportsReasoning: false,
    supportedLanguages: ["en", "zh"],
  },
  "z-ai/glm5": {
    id: "z-ai/glm5",
    name: "GLM-5",
    description: "Zhipu AI's GLM-5 model specialized in software development and architecture - excels at code generation, debugging, refactoring, and system design",
    category: "code",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    license: "Z.ai License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["4x GB200", "4x B200"],
    supportedHardware: ["Blackwell", "Hopper"],
    runtimeEngines: ["vLLM"],
    tags: ["coding", "software-engineering", "agentic", "reasoning", "commercial"],
    supportsReasoning: true,
    reasoningModes: ["enabled", "disabled"],
    supportedLanguages: ["en", "zh"],
  },
  // === Embeddings ===
  "nvidia/nv-embedqa-e5-v5": {
    id: "nvidia/nv-embedqa-e5-v5",
    name: "NV-EmbedQA E5 v5",
    description: "NVIDIA embedding model optimized for Q&A retrieval",
    category: "embedding",
    contextLength: 512,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    license: "NVIDIA Open Model License",
    commercialUse: true,
    thirdPartyModel: false,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["Transformers", "vLLM"],
    tags: ["embedding", "rag", "qa", "retrieval"],
    supportedLanguages: ["en"],
  },
  "nvidia/nv-embed-v1": {
    id: "nvidia/nv-embed-v1",
    name: "NV-Embed v1",
    description: "NVIDIA general purpose embedding model",
    category: "embedding",
    contextLength: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    license: "NVIDIA Open Model License",
    commercialUse: true,
    thirdPartyModel: false,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["Transformers", "vLLM"],
    tags: ["embedding", "rag", "general-purpose", "retrieval"],
    supportedLanguages: ["en"],
  },
  "baai/bge-m3": {
    id: "baai/bge-m3",
    name: "BGE-M3",
    description: "Multilingual embedding model",
    category: "embedding",
    contextLength: 8192,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["Transformers", "vLLM"],
    tags: ["embedding", "multilingual", "rag", "retrieval"],
    supportedLanguages: ["en", "zh", "ja", "ko", "fr", "de", "es", "ru", "ar", "pt", "it"],
  },
  // === Reranking ===
  "nvidia/nv-rerankqa-mistral-4b-v3": {
    id: "nvidia/nv-rerankqa-mistral-4b-v3",
    name: "NV-RerankQA Mistral 4B v3",
    description: "NVIDIA reranking model for RAG pipelines",
    category: "reranking",
    contextLength: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    license: "NVIDIA Open Model License",
    commercialUse: true,
    thirdPartyModel: false,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["Transformers", "vLLM"],
    tags: ["reranking", "rag", "retrieval"],
    supportedLanguages: ["en"],
  },
  // === Image Generation ===
  "nvidia/stable-diffusion-xl": {
    id: "nvidia/stable-diffusion-xl",
    name: "Stable Diffusion XL",
    description: "High-quality text-to-image generation model from Stability AI. Three times larger UNet backbone with second text encoder.",
    category: "image_generation",
    contextLength: 77,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    supportsImageGeneration: true,
    maxTokens: 77,
    recommendedUseCases: [
      "Artistic image generation",
      "Concept art",
      "Marketing materials",
      "Product visualization",
      "Creative design",
    ],
    license: "SDXL 1.0 License (Stability AI membership required)",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB", "1x H100 80GB"],
    supportedHardware: ["Hopper", "Ampere", "Turing"],
    runtimeEngines: ["Triton"],
    imageGenSpecs: {
      supportedResolutions: ["1024x1024", "1152x896", "896x1152", "1216x832", "832x1216"],
      supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      maxImagesPerRequest: 4,
      recommendedSamplers: ["euler", "euler_a", "dpmpp_2m", "dpmpp_sde", "ddim"],
      recommendedSchedulers: ["karras", "exponential", "simple", "ddim_uniform"],
      defaultSteps: 20,
      defaultCfgScale: 7.0,
      supportsNegativePrompt: true,
      supportsImageToImage: false,
      supportsInpainting: false,
      supportsControlNet: false,
    },
    tags: ["text-to-image", "artistic", "high-quality", "stable-diffusion"],
  },
  "nvidia/sdxl-turbo": {
    id: "nvidia/sdxl-turbo",
    name: "SDXL Turbo",
    description: "Fast text-to-image generation with fewer steps (1-4 steps). Adversarial Diffusion Distillation.",
    category: "image_generation",
    contextLength: 77,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    supportsImageGeneration: true,
    maxTokens: 77,
    recommendedUseCases: [
      "Real-time image generation",
      "Rapid prototyping",
      "Interactive applications",
    ],
    license: "SDXL 1.0 License (Stability AI membership required)",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Ampere"],
    runtimeEngines: ["Triton"],
    imageGenSpecs: {
      supportedResolutions: ["512x512", "1024x1024"],
      supportedAspectRatios: ["1:1"],
      maxImagesPerRequest: 4,
      recommendedSamplers: ["euler", "euler_a"],
      recommendedSchedulers: ["simple"],
      defaultSteps: 1,
      defaultCfgScale: 1.0,
      supportsNegativePrompt: true,
      supportsImageToImage: false,
      supportsInpainting: false,
      supportsControlNet: false,
    },
    tags: ["text-to-image", "fast", "real-time", "turbo", "stable-diffusion"],
  },
  "stabilityai/sd-3-medium": {
    id: "stabilityai/sd-3-medium",
    name: "Stable Diffusion 3 Medium",
    description: "Latest Stable Diffusion 3 model with improved prompt adherence and better text rendering.",
    category: "image_generation",
    contextLength: 77,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    supportsImageGeneration: true,
    maxTokens: 77,
    recommendedUseCases: [
      "High-fidelity image generation",
      "Complex prompt following",
      "Typography and text in images",
    ],
    license: "Stability AI Membership License",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB", "1x H100 80GB"],
    supportedHardware: ["Hopper", "Ampere"],
    runtimeEngines: ["Triton"],
    imageGenSpecs: {
      supportedResolutions: ["1024x1024", "1152x896", "896x1152", "1216x832", "832x1216"],
      supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      maxImagesPerRequest: 2,
      recommendedSamplers: ["euler", "euler_a", "dpmpp_2m"],
      recommendedSchedulers: ["karras", "exponential"],
      defaultSteps: 20,
      defaultCfgScale: 7.0,
      supportsNegativePrompt: true,
      supportsImageToImage: false,
      supportsInpainting: false,
      supportsControlNet: false,
    },
    tags: ["text-to-image", "high-fidelity", "prompt-adherence", "typography", "sd3"],
  },
  "black-forest-labs/flux.1-dev": {
    id: "black-forest-labs/flux.1-dev",
    name: "FLUX.1 [dev]",
    description: "State-of-the-art text-to-image model from Black Forest Labs. Diffusion Transformer architecture. Supports Canny and Depth ControlNet variants.",
    category: "image_generation",
    contextLength: 512,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    supportsImageGeneration: true,
    maxTokens: 512,
    recommendedUseCases: [
      "Photorealistic image generation",
      "Complex scene composition",
      "High-quality artistic renderings",
    ],
    license: "Apache 2.0 (non-commercial default, commercial via contact)",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["1x H100 80GB", "1x B200"],
    supportedHardware: ["Blackwell", "Hopper", "Lovelace"],
    runtimeEngines: ["TensorRT"],
    imageGenSpecs: {
      supportedResolutions: ["1024x1024", "1152x896", "896x1152", "1344x768", "768x1344"],
      supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9", "9:21"],
      maxImagesPerRequest: 1,
      recommendedSamplers: ["euler", "euler_a"],
      recommendedSchedulers: ["simple"],
      defaultSteps: 20,
      defaultCfgScale: 3.5,
      supportsNegativePrompt: true,
      supportsImageToImage: true,
      supportsInpainting: true,
      supportsControlNet: true,
    },
    tags: ["text-to-image", "photorealistic", "flux", "controlnet", "controlnet-canny", "controlnet-depth"],
  },
  "black-forest-labs/flux.1-kontext-dev": {
    id: "black-forest-labs/flux.1-kontext-dev",
    name: "FLUX.1 Kontext [dev]",
    description: "FLUX.1 variant for image-to-image editing with context preservation. Supports inpainting, outpainting, style transfer with layout preservation.",
    category: "image_generation",
    contextLength: 512,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    supportsImageGeneration: true,
    maxTokens: 512,
    recommendedUseCases: [
      "Image editing with context preservation",
      "Inpainting and outpainting",
      "Style transfer with layout preservation",
      "Character consistency across images",
    ],
    license: "Apache 2.0 (non-commercial default, commercial via contact)",
    commercialUse: false,
    thirdPartyModel: true,
    minGpuRequirements: ["1x H100 80GB", "1x B200"],
    supportedHardware: ["Blackwell", "Hopper", "Lovelace"],
    runtimeEngines: ["TensorRT"],
    imageGenSpecs: {
      supportedResolutions: ["1024x1024", "1152x896", "896x1152", "1344x768", "768x1344"],
      supportedAspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9", "9:21"],
      maxImagesPerRequest: 1,
      recommendedSamplers: ["euler", "euler_a"],
      recommendedSchedulers: ["simple"],
      defaultSteps: 20,
      defaultCfgScale: 3.5,
      supportsNegativePrompt: true,
      supportsImageToImage: true,
      supportsInpainting: true,
      supportsControlNet: false,
    },
    tags: ["image-to-image", "editing", "inpainting", "outpainting", "style-transfer", "flux", "character-consistency"],
  },
  // === Multimodal ===
  "nvidia/neva-22b": {
    id: "nvidia/neva-22b",
    name: "NeVA 22B",
    description: "NVIDIA's multimodal model for image understanding and reasoning",
    category: "multimodal",
    contextLength: 4096,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsVision: true,
    recommendedUseCases: [
      "Image captioning",
      "Visual question answering",
      "Document understanding",
      "Scene analysis",
    ],
    license: "NVIDIA Open Model License",
    commercialUse: true,
    thirdPartyModel: false,
    minGpuRequirements: ["1x H100 80GB"],
    supportedHardware: ["Hopper", "Blackwell"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["multimodal", "vision", "captioning", "vqa", "document-analysis"],
    supportedLanguages: ["en"],
  },
  "microsoft/phi-3.5-vision-instruct": {
    id: "microsoft/phi-3.5-vision-instruct",
    name: "Phi-3.5 Vision Instruct",
    description: "Microsoft's efficient vision-language model",
    category: "multimodal",
    contextLength: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: false,
    supportsVision: true,
    recommendedUseCases: [
      "Image analysis",
      "Chart and diagram understanding",
      "OCR and document processing",
      "Visual reasoning",
    ],
    license: "MIT",
    commercialUse: true,
    thirdPartyModel: true,
    minGpuRequirements: ["1x A100 40GB"],
    supportedHardware: ["Hopper", "Blackwell", "Ampere"],
    runtimeEngines: ["vLLM", "SGLang"],
    tags: ["multimodal", "vision", "ocr", "charts", "document-processing", "efficient"],
    supportedLanguages: ["en"],
  },
};

export function getModelsByCategory(category: ModelCategory): NIMModel[] {
  return Object.values(NIM_MODELS).filter((m) => m.category === category);
}

export function getModel(modelId: string): NIMModel | undefined {
  return NIM_MODELS[modelId];
}
